### ISSUE TITLE
Typescript errors in wonka 6.3.3

### ISSUE THREAD

**Issue by mshogren** [0no-co/wonka#167]
Building my project works correctly with wonka v6.3.2, but not with v6.3.3.  The issue is that typescript finds a issues in wonka.d.ts 

> node_modules/wonka/dist/wonka.d.ts:1323:13 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.
> 
> 1323     [Symbol.observable]?(): Observable<T>;
>                  ~~~~~~~~~~
>                  
> node_modules/wonka/dist/wonka.d.ts:1352:13 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.
> 
> 1352     [Symbol.observable](): Observable<T>;
>                  ~~~~~~~~~~

This can be resolved by adding the following block to the wonka.d.ts file

```
declare global {
  interface SymbolConstructor {
    readonly observable: symbol;
  }
}
```

It appears that this was recently moved from the observable.ts file to the helpers.ts file, but I can't tell why it doesn't appear in the finished wonka.d.ts file, but it could be that index.ts doesn't contain a line like

`export * from './helpers';`

I will continue to look into this when I have more time.

**Comment by kitten** [comment]
Nice catch! I didn't actually notice that this went missing. I guess I didn't remember to check. I've moved it back and added a comment to prevent this from happening again. I think these issues always have a delay in being reported since `skipLibCheck: true` is a common option to have enabled in most scenarios
